name: presensi_smkn1punggelan
description: A new Flutter project.
publish_to: 'none'
version: 1.5.1+7

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  get_it: ^8.0.2
  shared_preferences: ^2.2.3
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.20.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_osm_plugin: ^1.0.5
  geolocator: ^13.0.2
  device_info_plus: ^11.1.1
  flutter_face_api: ^6.2.2
  flutter_face_core_basic: ^6.2.1
  flutter_local_notifications: ^18.0.1
  dio: ^5.7.0 # Add this line if dio is missing
  timezone: ^0.10.0 # Add this line if timezone is missing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_foreground_scale_factor: 0.5
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"